import test from 'node:test';import assert from 'node:assert/strict';
import {initial,empty,play,collapseAfterMove} from '../dist/engine.js';
test('150手から両陣営の駒を抽選し持ち駒は維持',()=>{let s=initial();s.moveLimit=false;s.ply=148;s.paradoxAt=150;s=collapseAfterMove(play(s,{from:54,to:45,prom:false}),()=>0);assert.equal(s.destroyed,null);s=collapseAfterMove(play(s,{from:18,to:27,prom:false}),()=>0);assert.equal(s.ply,150);assert.equal(s.paradoxStarted,true);assert.equal(s.destroyed.piece.side,1);assert.equal(s.board.filter(Boolean).length,39);assert.deepEqual(s.hands,[{},{}]);s=collapseAfterMove(play(s,{from:55,to:46,prom:false}),()=>0);assert.equal(s.paradoxStarted,false);assert.equal(s.destroyed.piece.side,1);assert.equal(s.board.filter(Boolean).length,38);});
test('王も抽選対象、壊れた側が負ける',()=>{const s=empty();s.moveLimit=false;s.paradoxAt=1;s.board[76]={type:'K',side:0};s.board[4]={type:'K',side:1};const n=collapseAfterMove(play(s,{from:76,to:75,prom:false}),()=>0);assert.equal(n.destroyed.piece.type,'K');assert.match(n.result,/先手の勝ち.*王が崩壊/);});
test('通常勝利と60手判定は崩壊より優先',()=>{let s=initial();s.ply=59;s.paradoxAt=60;const n=collapseAfterMove(play(s,{from:54,to:45,prom:false}),()=>{throw Error('should not roll');});assert.match(n.result,/60手/);assert.equal(n.destroyed,null);});

test('無制限の盤面崩壊は150手を過ぎても発動しない',()=>{const s=initial();s.moveLimit=false;s.paradoxAt=false;s.ply=200;const n=collapseAfterMove(play(s,{from:54,to:45,prom:false}),()=>{throw Error('must not roll');});assert.equal(n.destroyed,null);assert.equal(n.board.filter(Boolean).length,40);});

test('味方の王が崩壊すると相手の勝ち',()=>{const s=empty();s.moveLimit=false;s.paradoxAt=1;s.board[76]={type:'K',side:0};s.board[4]={type:'K',side:1};const n=collapseAfterMove(play(s,{from:76,to:75,prom:false}),n=>n-1);assert.equal(n.destroyed.piece.side,0);assert.match(n.result,/後手の勝ち/);});
test('盤面崩壊では破壊の代わりに大駒が空きマスへ現れることがある',()=>{let s=initial();s.moveLimit=false;s.paradoxAt=1;const picks=[0,1,0],n=collapseAfterMove(play(s,{from:54,to:45,prom:false}),size=>picks.shift()%size,()=>true);assert.equal(n.destroyed,null);assert.equal(n.spawned.piece.type,'R');assert.equal(n.spawned.piece.side,0);assert.deepEqual(n.board[n.spawned.square],n.spawned.piece);});
